#!/bin/sh
DATA="token=$API_KEY&content=record&action=export&format=csv&type=flat&csvDelimiter=&rawOrLabel=label&rawOrLabelHeaders=raw&exportCheckboxLabel=false&exportSurveyFields=false&exportDataAccessGroups=false&returnFormat=json"
CURL=`which curl`
$CURL -H "Content-Type: application/x-www-form-urlencoded" \
      -H "Accept: application/json" \
      -X POST \
      -d $DATA \
      https://redcap.mountsinai.org/redcap/api/ > input.csv
