#!/bin/sh
DATA=""
CURL=`which curl`
$CURL -H "Content-Type: application/x-www-form-urlencoded" \
      -H "Accept: application/json" \
      -X POST \
      -d $DATA \
      https://redcap.mountsinai.org/redcap/api/ > input.csv
