name: Deploy Shiny app

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v1

      - name: Install required packages
        run: |
          Rscript -e 'install.packages(c("httr", "DT", "rsconnect", "tidyverse"))'

      - name: API pull
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: api-get

      - name: ETL script
        run: Rscript etl.R

      - name: Deploy Shiny app
        env:
          SHINYAPPSIO_ACCOUNT: ctastad
          SHINYAPPSIO_TOKEN: ${{ secrets.SHINYAPPSIO_TOKEN }}
        run: |
          R -e "library(rsconnect); options(rsconnect.show.traceback = TRUE); rsconnect::setAccountInfo(name = Sys.getenv('SHINYAPPSIO_ACCOUNT'), token = Sys.getenv('SHINYAPPSIO_TOKEN')); rsconnect::deployApp('scmeta-table/app.R')"
