name: Deploy Shiny app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
          r-version: ['4.2.1']

    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages(c("httr", "DT", "rsconnect", "tidyverse"))
        shell: Rscript {0}
      - name: API pull
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: ./api-get
      - name: ETL script
        run:  etl.R
        shell: Rscript {0}
      - name: Deploy Shiny app
        env:
          SHINYAPPSIO_TOKEN: ${{ secrets.SHINYAPPSIO_TOKEN }}
        run: |
          library(rsconnect)
          setAccountInfo(name='ctastad', token='${SHINYAPPSIO_TOKEN}')
          deployApp(appName = ' chobiolab-scmeta-table ', appDir = 'scmeta-table/app.R')
        shell: Rscript {0}
